---
- hosts: redmine
  become: yes
  gather_facts: false
  tasks:
    - wait_for_connection:

    - setup:
    
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true
      become: yes

    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg
          - gpg
          - python3
          - python3-pip
          - openssl
          - git
          - tmux
        state: latest
        update_cache: true
      register: output
      become: yes

    - name: Show results
      ansible.builtin.debug:
        var: output
      become: yes

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
      become: yes

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/debian bookworm stable
        state: present
      become: yes
    
    - name: Install docker and docker compose
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - docker-compose-plugin
          - docker-buildx-plugin
          - containerd.io
        state: latest
        update_cache: true
      register: output
      become: yes

    - name: Show results
      ansible.builtin.debug:
        var: output
      become: yes